# Generated by Django 5.1.7 on 2025-03-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0003_alter_position_name_alter_tasktype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
    ]
